import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  userSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started-user'}],
    },
    {
      type: 'category',
      label: 'User Guide',
      collapsed: true,
      items: [
        'user-guide/intro',
        'user-guide/browser-compatibility',
        {
          type: 'category',
          label: 'Your Wallet',
          items: [{type: 'autogenerated', dirName: 'user-guide/wallet'}],
        },
        {
          type: 'category',
          label: 'Security & Privacy',
          items: [{type: 'autogenerated', dirName: 'user-guide/security'}],
        },
        {
          type: 'category',
          label: 'Settings',
          items: [{type: 'autogenerated', dirName: 'user-guide/settings'}],
        },
        {
          type: 'category',
          label: 'Troubleshooting',
          items: [{type: 'autogenerated', dirName: 'user-guide/troubleshooting'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'tutorials-user'}],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [{type: 'autogenerated', dirName: 'faq-user'}],
    }
  ],
  integratorSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'getting-started-integrator'}],
    },
    {
      type: 'category',
      label: 'Integration Guide',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Integration Patterns',
          items: [{type: 'autogenerated', dirName: 'integrator-guide/integration-patterns'}],
        },
        {
          type: 'category',
          label: 'Best Practices',
          items: [{type: 'autogenerated', dirName: 'integrator-guide/best-practices'}],
        },
        {
          type: 'category',
          label: 'Code Examples',
          items: [{type: 'autogenerated', dirName: 'integrator-guide/examples'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Endpoints',
          items: [{type: 'autogenerated', dirName: 'api-reference/endpoints'}],
        },
        {
          type: 'category',
          label: 'Authentication',
          items: [{type: 'autogenerated', dirName: 'api-reference/authentication'}],
        },
        {
          type: 'category',
          label: 'Errors',
          items: [{type: 'autogenerated', dirName: 'api-reference/errors'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'SDK Reference',
      items: [{type: 'autogenerated', dirName: 'sdk-reference'}],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'tutorials-integrator'}],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [{type: 'autogenerated', dirName: 'faq-integrator'}],
    }
  ],
  changelogSidebar: [
    {
      type: 'category',
      label: 'Changelog',
      items: [{type: 'autogenerated', dirName: 'changelog'}],
    },
  ]
};

export default sidebars;
