import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  usersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'users',
    },
  ],
  integratorsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'integrators',
    },
  ],
  developersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'developers',
    },
  ],
};

export default sidebars;
